---

stages:
  - prepare
  - build
  - release
  - trigger

prepare:
  stage: prepare
  tags:
    - dockerwest
  script:
    - docker pull debian:stretch-slim
  only:
    - master

build:5.6:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 5.6; ./build.sh
  only:
    - master

build:7.0:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.0; ./build.sh
  only:
    - master

build:7.1:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.1; ./build.sh
  only:
    - master

build:7.2:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.2; ./build.sh
  only:
    - master

build:7.3:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.3; ./build.sh
  only:
    - master

build:7.4:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 7.4; ./build.sh
  only:
    - master

build:8.0:
  stage: build
  tags:
    - dockerwest
  script:
    - cd 8.0; ./build.sh
  only:
    - master

release:5.6:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php:5.6
  only:
    - master

release:7.0:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php:7.0
  only:
    - master

release:7.1:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php:7.1
  only:
    - master

release:7.2:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php:7.2
  only:
    - master

release:7.3:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php:7.3
  only:
    - master

release:7.4:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php:7.4
  only:
    - master

release:8.0:
  stage: release
  tags:
    - dockerwest
  script:
    - docker push dockerwest/php:8.0
  only:
    - master

trigger:php-laravel:
  stage: trigger
  trigger:
    project: DockerWest/php-laravel

trigger:php-magento1:
  stage: trigger
  trigger:
    project: DockerWest/php-magento1

trigger:php-magento2:
  stage: trigger
  trigger:
    project: DockerWest/php-magento2

trigger:php-pimcore:
  stage: trigger
  trigger:
    project: DockerWest/php-pimcore

trigger:php-symfony:
  stage: trigger
  trigger:
    project: DockerWest/php-symfony

trigger:php-sylius:
  stage: trigger
  trigger:
    project: DockerWest/php-sylius
